# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a682bb99fa39c17d37a84cb14679874b04a0e53fe400b4a9db3a0c79698418815fcdae09b51273d578d3c206acb14ea669efd0e77e3c7dd4058da12ed6a27e1

test:
  secret_key_base: 33470853bb46104dd915b682c961dddc4787c291df828c0a7116fa5bcac35804037519c55659285961941c84414726a2e6a35184fd759c4f48e03fed37afc4fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
